import os
import re
import json
import asyncio
import traceback
from typing import Any
from pydantic import BaseModel, Field
from google.adk.agents import LlmAgent
from google.adk.tools import AgentTool
from google.adk.tools.mcp_tool import McpToolset
from google.adk.tools.mcp_tool.mcp_session_manager import StdioConnectionParams
from mcp import StdioServerParameters
from google.adk.workflow import Workflow, START, node
from google.adk.events.event import Event
from google.adk.events.request_input import RequestInput
from google.adk.agents.context import Context
from google.adk.apps import App, ResumabilityConfig
from google.genai import types

from .config import config

# --- 1. Structured Output Schema ---

class SoftwarePackage(BaseModel):
    project_name: str = Field(description="The name of the software project (lowercase, hyphens, <=26 chars).")
    product_requirements: str = Field(description="Detailed Product Requirements Document (PRD) generated by pm_agent.")
    system_architecture: str = Field(description="System architecture design, including database schema and API structure generated by architect_agent.")
    ceo_summary: str = Field(description="CEO executive summary and task roadmap.")


# --- 2. MCP Toolset Setup ---

mcp_connection = StdioConnectionParams(
    server_params=StdioServerParameters(
        command="uv",
        args=["run", "python", "-m", "app.mcp_server"],
    )
)

pm_mcp_toolset = McpToolset(
    connection_params=mcp_connection,
    tool_filter=["estimate_development_time"],
)

architect_mcp_toolset = McpToolset(
    connection_params=mcp_connection,
    tool_filter=["validate_package_structure", "generate_boilerplate_structure"],
)


# --- 3. Specialized LlmAgents (Sub-agents) ---

pm_agent = LlmAgent(
    name="pm_agent",
    model=config.model,
    instruction="""You are the Product Manager (PM) for DevForge AI.
Your role is to analyze a product description and write a comprehensive Product Requirements Document (PRD).
Ensure you estimate the development time using the 'estimate_development_time' tool.
Define user personas, key features, functional requirements, and user stories.
Structure your output professionally using Markdown.""",
    description="Generates detailed Product Requirements Documents (PRDs) for software projects.",
    tools=[pm_mcp_toolset],
)

architect_agent = LlmAgent(
    name="architect_agent",
    model=config.model,
    instruction="""You are the Software Architect for DevForge AI.
Your role is to design the technical architecture for the project.
First, generate standard project structure guidelines using 'generate_boilerplate_structure'.
Then validate your proposed layout using 'validate_package_structure'.
Provide a system architecture description, database schemas (e.g. PostgreSQL tables), API designs (REST endpoints/schemas), and file structure.
Structure your output professionally using Markdown.""",
    description="Designs database schemas, system architecture, and API endpoints for software projects.",
    tools=[architect_mcp_toolset],
)


# --- 4. CEO Orchestrator LlmAgent ---

ceo = LlmAgent(
    name="ceo",
    model=config.model,
    instruction="""You are the CEO of DevForge AI, an autonomous software development company.
Your goal is to coordinate your team to deliver a premium software starter package.
When the user requests a software project, you must delegate:
1. Product management task to 'pm_agent' to generate the PRD.
2. System architecture task to 'architect_agent' to generate the database schema and API design.

Review their outputs, combine them, and add your CEO summary. Return the final unified software specification package.
""",
    tools=[AgentTool(pm_agent), AgentTool(architect_agent)],
    output_key="software_package",
)



# --- 4. Workflow Function Nodes ---

def security_checkpoint(ctx: Context, node_input: types.Content) -> Event:
    """Initial check for PII, prompt injections, and request validation."""
    user_text = ""
    if hasattr(node_input, "parts") and node_input.parts:
        user_text = "".join(part.text for part in node_input.parts if hasattr(part, "text") and part.text)
    elif isinstance(node_input, str):
        user_text = node_input

    # 1. Prompt Injection keyword detection
    injection_keywords = ["ignore previous", "bypass security", "dan mode", "ignore instructions", "override model"]
    if any(kw in user_text.lower() for kw in injection_keywords):
        audit_log = {
            "severity": "CRITICAL",
            "event": "prompt_injection_detected",
            "query": user_text,
            "reason": "Found injection keywords"
        }
        print(json.dumps(audit_log))
        return Event(
            output="Security Event: Prompt injection attempt detected and blocked.",
            route="SECURITY_EVENT"
        )

    # 2. PII Scrubbing (emails, phone numbers, and Google API keys)
    scrubbed_text = user_text
    scrubbed_text = re.sub(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b", "[EMAIL_SCRUBBED]", scrubbed_text)
    scrubbed_text = re.sub(r"\b\d{3}[-.]?\d{3}[-.]?\d{4}\b", "[PHONE_SCRUBBED]", scrubbed_text)
    scrubbed_text = re.sub(r"\b(AIzaSy[A-Za-z0-9-_]{33})\b", "[GOOGLE_API_KEY_SCRUBBED]", scrubbed_text)

    # 3. Domain-Specific Rule: Ensure request is software/tech development related
    tech_keywords = ["app", "system", "build", "create", "website", "tool", "service", "api", "platform", "program", "software", "database", "design", "tracker", "development"]
    if not any(kw in scrubbed_text.lower() for kw in tech_keywords):
        audit_log = {
            "severity": "WARNING",
            "event": "domain_violation",
            "query": scrubbed_text,
            "reason": "Request is not software-development related"
        }
        print(json.dumps(audit_log))
        return Event(
            output="Security Event: Request is not software or technology development related.",
            route="SECURITY_EVENT"
        )

    # Successful pass audit log
    audit_log = {
        "severity": "INFO",
        "event": "security_checkpoint_passed",
        "scrubbed": scrubbed_text != user_text
    }
    print(json.dumps(audit_log))

    return Event(
        output=scrubbed_text,
        route="pass",
        state={"user_request": scrubbed_text}
    )


def security_event(node_input: str) -> Event:
    """Handles and reports security violations."""
    # Yield content for the playground UI
    yield Event(content=types.Content(role='model', parts=[types.Part.from_text(text=f"⚠️ {node_input}")]))
    yield Event(output=node_input)


@node(rerun_on_resume=True)
async def run_ceo_with_retry(ctx: Context, node_input: str) -> Event:
    """Wrapper node for executing the CEO orchestrator with backoff retry logic on API errors."""
    max_retries = 5
    delays = [1, 2, 4, 8, 16]

    for attempt in range(max_retries):
        try:
            # Run the CEO orchestrator node using run_node
            ceo_output = await ctx.run_node(ceo, node_input=node_input)
            yield Event(output=ceo_output)
            return  # Success, exit the retry loop
        except Exception as e:
            # If it is the last attempt, fail gracefully and display error
            if attempt == max_retries - 1:
                err_msg = traceback.format_exc()
                # Log to stdout/stderr
                print(f"ERROR: CEO agent failed after all retries:\n{err_msg}")
                # Yield UI message
                yield Event(content=types.Content(role='model', parts=[types.Part.from_text(
                    text=f"❌ Error: The AI service is currently unavailable. Please try again later. (Details: {str(e)})"
                )]))
                # Deliver a clean string exit instead of crashing
                yield Event(output=f"Error: AI service unavailable. details: {str(e)}")
                return

            # Yield user-friendly UI warning
            retry_msg = f"⏳ AI service is temporarily busy, retrying (attempt {attempt + 1}/{max_retries}) in {delays[attempt]}s..."
            yield Event(content=types.Content(role='model', parts=[types.Part.from_text(text=retry_msg)]))
            
            # Log progress
            print(f"WARNING: CEO attempt {attempt + 1} failed with error: {str(e)}. Retrying in {delays[attempt]}s...")
            
            # Delay with backoff
            await asyncio.sleep(delays[attempt])


async def human_review(ctx: Context, node_input: Any) -> Event:
    """Asks for human approval before delivering the package."""
    # Extract the text generated by the CEO
    user_text = ""
    if isinstance(node_input, str):
        user_text = node_input
    elif isinstance(node_input, dict):
        user_text = json.dumps(node_input, indent=2)
    elif hasattr(node_input, "parts") and node_input.parts:
        user_text = "".join(part.text for part in node_input.parts if hasattr(part, "text") and part.text)
    else:
        user_text = str(node_input)

    if not ctx.resume_inputs or "approval" not in ctx.resume_inputs:
        yield RequestInput(
            interrupt_id="approval",
            message="Please review the generated software specification. Type 'approve' to proceed, or provide feedback for revision."
        )
        return

    response = ctx.resume_inputs["approval"]
    
    # Audit log
    print(json.dumps({
        "severity": "INFO",
        "event": "human_review",
        "action": "resolved",
        "approval": response
    }))

    yield Event(
        output=user_text,
        state={"approval_response": response, "approved": True}
    )


def final_output(ctx: Context, node_input: Any) -> Event:
    """Formats and displays the final approved software package."""
    output_text = f"""# 🚀 DevForge AI — Final Software Package

{node_input}
"""

    yield Event(content=types.Content(role='model', parts=[types.Part.from_text(text=output_text)]))
    yield Event(output=node_input)


# --- 5. Graph Topology & Workflow Definition ---

edges = [
    (START, security_checkpoint),
    (security_checkpoint, {"pass": run_ceo_with_retry, "SECURITY_EVENT": security_event}),
    (run_ceo_with_retry, human_review),
    (human_review, final_output),
]

root_agent = Workflow(
    name="devforge_workflow",
    edges=edges,
    description="Coordinates CEO, PM, and Software Architect sub-agents for software specifications."
)

app = App(
    root_agent=root_agent,
    name="app",
    resumability_config=ResumabilityConfig(is_resumable=True)
)
